### ISSUE TITLE
[Not a Bug] A good library, but can it be combined with the Alfred library?

### ISSUE THREAD

**Issue by azkadev** [Hawmex/navand#1]
Your library is good because it uses the flutter style, but can it be combined with the [ALFRED](https://pub.dev/packages/alfred) library?

**Comment by Hawmex** [comment]
Thanks. Can you clarify what you mean by "combine"?

As far as I know, you can connect your Navand frontend app to any backend framework, just like a `create-react-app`.

**Comment by Hawmex** [comment]
Closing the issue since it has been inactive. Feel free to reopen it.
